### ISSUE TITLE
Confusing/misleading error messages on test failures.

### ISSUE THREAD

**Issue by sengi** [alphagov/smokey#1080]
There's something about the way Sentry is configured in Smokey that leads to misleading error logs like this when a test fails.

In this example, a network request to the application under test has timed out. From the error messages, it'd be easy to think that the test is broken because of something to do with Sentry, but this isn't the case.

This isn't an isolated example; pretty much any test failure that results in an exception in the test runner looks similar to this.

```
  @app-publishing-api
  Scenario: Can log in to imminence           # features/apps/imminence.feature:4
    When I go to the "imminence" landing page # features/step_definitions/smokey_steps.rb:46
      application_external_url(imminence) = 'https://imminence.integration.publishing.service.gov.uk/admin'
      Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
      ./features/support/visiting_pages.rb:7:in `visit_path'
      ./features/step_definitions/smokey_steps.rb:47:in `/^I go to the "([^"]*)" landing page$/'
      features/apps/imminence.feature:5:in `I go to the "imminence" landing page'
    And I try to login as a user              # features/step_definitions/signon_steps.rb:1
    And I go to the "imminence" landing page  # features/step_definitions/smokey_steps.rb:46
    Then I should see "GOV.UK Imminence"      # features/step_definitions/smokey_steps.rb:160
    And I should see "Sign out"               # features/step_definitions/smokey_steps.rb:160
    And I should see "All services"           # features/step_definitions/smokey_steps.rb:160
E, [2023-01-16T13:03:51.781156 #26604] ERROR -- sentry: ** [Sentry] Event sending failed: undefined method `underscore' for "ReadTimeout":String
I, [2023-01-16T13:03:51.781423 #26604]  INFO -- sentry: ** [Sentry] Unreported Event: features/apps/imminence.feature

Net::ReadTimeout
E, [2023-01-16T13:03:51.781475 #26604] ERROR -- sentry: ** [Sentry] exception happened in background worker: undefined method `underscore' for "ReadTimeout":String
```

**Comment by sengi** [comment]
Thanks for fixing this! ❤️
