### ISSUE TITLE
AJAX tests are sometimes rate limited (HTTP 429)

### ISSUE THREAD

**Issue by benthorner** [alphagov/smokey#926]
## Problem

Example:

```
      ./features/step_definitions/feedback_steps.rb:62:in `/^I see the feedback confirmation message$/'
      features/feedback.feature:25:in `I see the feedback confirmation message'
    And a request is sent to the feedback app         # features/step_definitions/feedback_steps.rb:69
2022-05-04 12:36:43 WARN Selenium [DEPRECATION] Manager#logs is deprecated. Use Chrome::Driver#logs instead.
📜   severe 
     https://www.integration.publishing.service.gov.uk/contact/govuk/email-survey-signup - Failed to load resource: the server responded with a status of 429 (Too Many Requests)
      Got some JS errors during testing:
      
      📜   severe 
           https://www.integration.publishing.service.gov.uk/contact/govuk/email-survey-signup - Failed to load resource: the server responded with a status of 429 (Too Many Requests) (Capybara::Chromedriver::Logger::JsError)
      ./features/support/hooks.rb:25:in `flush_and_check_errors'
      ./features/support/hooks.rb:9:in `After'
```

This happens infrequently on Integration but can be reproduced reliably by modifying [the above scenario in feedback.feature](https://github.com/alphagov/smokey/blob/a3fcb56fc72c015c7de6af9d11817da856432da9/features/feedback.feature#L21) to increase the number of requests made within a short period:

```
  Scenario: Check "is this page useful?" email survey
    When I visit "/"
    And I click to say the page is not useful
    And I submit the email survey signup form
    When I visit "/"
    And I click to say the page is not useful
    And I submit the email survey signup form
    When I visit "/"
    And I click to say the page is not useful
    And I submit the email survey signup form
    ... (only one or two repetitions is necessary)
```

It looks this is actually a new problem due to https://github.com/alphagov/feedback/pull/1390, which doesn't honour rate limit bypass (even if the header is sent). Testing with a previous version of the Feedback app resolves the issue*.

*It is still possible to get a HTTP 429 rate limit error without [rate limit bypass](https://github.com/alphagov/smokey/pull/918), but only higher number of repeat requests e.g. 3 or 4 repetitions of the above example. As per the removal PR, this is relaxed enough to not be an issue.

## Solutions

One option would be to fix [the old rate limit bypass approach](https://github.com/alphagov/smokey/pull/918) ([or the recommended alternative](https://github.com/alphagov/smokey/pull/918#issuecomment-1117295679)) and then fix whatever is causing the token to be ignored upstream e.g. the CDN may be swallowing the header.

A simpler option might be to change [the rate limit bypass approach](https://github.com/alphagov/govuk-puppet/blob/b103dd3b4adcc8c39343dd85b68f4f5b93e38d9d/modules/router/templates/rate-limiting.conf.erb) to also look at the source IP address, such that all internal requests bypass rate limits by default. We may still need bypass tokens for other apps.

**Comment by benthorner** [comment]
## Update

It turns out this is actually a new problem due to https://github.com/alphagov/feedback/pull/1390, which doesn't honour rate limit bypass (even if the header is sent). Testing with a previous version of the Feedback app resolves the issue*.

*It is still possible to get a HTTP 429 rate limit error, but only higher number of repeat requests e.g. 3 or 4 repetitions of the above example. This is relaxed enough to not be an issue while we run Smokey serially.

**Comment by benthorner** [comment]
Fixed by https://github.com/alphagov/smokey/pull/952.
